### ISSUE TITLE
Q-22 Typo in answer

### ISSUE THREAD

**Issue by sumirmuku** [StenlyTU/K8s-training-official#10]
The corrected yaml is 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue1
spec:
  replicas: 5
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In
                  values:
                  - blue
 ```
