### ISSUE TITLE
Problem with question 22

### ISSUE THREAD

**Issue by alochym01** [StenlyTU/K8s-training-official#5]
there is mistype content of yaml file

The correct content yaml should be:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blue
  name: blue
  namespace: cka
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue
    spec:          
      affinity: # => miss indent
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
      containers:
      - image: nginx:1.18-alpine
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
```
